grep(".csv",list.files(),value=T)
getwd()
#setwd("C:/Users/Dell/Documents/DSR/Dataset")
dataset<-read.delim("bank-data.csv",sep=',')
dataset
head(dataset)
summary(dataset)
colnames((dataset))
ncol(dataset)
nrow(dataset)
str(dataset)
numbers<-seq(1,600)
numbers
new_dataset<-cbind(dataset,numbers)
new_dataset
colnames(new_dataset)
write.csv(new_dataset,'exportBankData.csv',row.names=FALSE)
getwd()